<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.3 setup script
 * Date: Sun, 09 Sep 2018 16:00:26 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: main_server_docker [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'main_server_docker';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '123456';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'O@Byoyqs*?9(9.l;10V^W#""Dksq@3|A';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>